apiVersion: v1
kind: Service
metadata:
  name: calculator-api-service
  namespace: default
spec:
  selector:
    app: calculator-api
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
